---
- name: Create Splunk group
  group:
    name: "{{ splunk_forwarder_group }}"
    gid: "{{ splunk_forwarder_gid }}"
    state: present
  tags: splunk_user

- name: Create Splunk user
  user:
    name: "{{ splunk_forwarder_user }}"
    group: "{{ splunk_forwarder_group }}"
    uid: "{{ splunk_forwarder_uid }}"
    state: present
  tags: splunk_user

- name: Get the RPM
  get_url:
    url: "{{ splunk_forwarder_rpm_url }}"
    dest: "/tmp/{{ splunk_forwarder_rpm }}"
  tags: install_splunk
  when: ansible_os_family == "RedHat"

- name: Check if the packages has already been downlaoded
  stat:
    path: /tmp/{{ splunk_forwarder_deb }}
  register: splunk_deb

- name: Get the deb
  command: curl -o /tmp/{{ splunk_forwarder_deb }} {{ splunk_forwarder_deb_url }}
  tags: install_splunk
  when: ansible_os_family == "Debian" and splunk_deb.stat.exists == False

- name: Install Splunk
  yum:
    name: "/tmp/{{ splunk_forwarder_rpm }}"
    state: present
  tags: install_splunk
  when: ansible_os_family == "RedHat"

- name: Install Splunk
  apt:
    deb: "/tmp/{{ splunk_forwarder_deb }}"
  tags: install_splunk
  when: ansible_os_family == "Debian"

- name: Copy inputs file
  copy:
    content: splunk_inputs_conf
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf
    backup: yes
  tags: config_copy

- name: Copy outputs file
  copy:
    content: splunk_outputs_conf
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    backup: yes
  tags: config_copy

- name: Upload Splunk startup script
  copy:
    src: splunk.deb
    dest: /etc/init.d/splunk
    owner: 0
    group: 0
    mode: 0755
  tags: splunk_startup
  notify: Enable Splunk Forwarder
  when: ansible_os_family == "Debian"

- name: Upload Splunk startup script
  copy:
    src: splunk
    dest: /etc/init.d/splunk
    owner: 0
    group: 0
    mode: 0755
  tags: splunk_startup
  notify: Enable Splunk Forwarder
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version <= "6"

- name: Upload Splunk Systemd Script
  copy:
    src: splunk.service
    dest: /usr/lib/systemd/system/splunk.service
    owner: 0
    group: 0
    mode: 0755
  tags: splunk_startup
  notify: Enable Splunk Forwarder
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >="7"
